version: '3.3'
services:
  todotask:
    container_name: todotask
    build:
      context: .
    ports:
      - 8000:8000
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - POSTGRESQL_URL=jdbc:postgresql://localhost:5432/todotask
    volumes:
      - ./:/app
    command: mvn cargo:run

  postgresqlserver:
    container_name: postgresql
    image: postgres:13.5-alpine
    ports:
      - 3306:5432
    environment:
      - POSTGRES_USER=pavel
      - POSTGRES_PASSWORD=pavel
      - POSTGRES_DB=todotask
    volumes:
      - postgres_data:/var/lib/postgresql
      - postgres_config:/etc/postgresql/13/main/conf.d
volumes:
  postgres_data:
  postgres_config:
